### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by seesharprun** [jaydestro/InvoiceGenerator#1]
- General

  - Consider the MIT license.

- Markdown

  - Consider placing the "getting started" section above the fold. This should be one of the first two sections you see in the readme instead of scrolling down.

  - Consider using a [mermaid](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams) diagram for your code section so you can list classes, methods, and descriptions.

  - There's no need to call `dotnet build` before `dotnet run`. The build step is implicitly ran if the project is not built.

- Code

  - Consider a library for command-line parsing so you don't have to "reinvent the wheel." [Sharprompt](https://github.com/shibayan/Sharprompt) has a healthy number of downloads on NuGet.

  - Consider running `dotnet format` on your code and adding it as part of the PR validation process.

  - Consider adding a solution file. This is now required for the new C# extension in Visual Studio Code.

  - Consider a unified namespace across the entire project.

  - Consider `sealed` classes if inheritance is not intended.

  - Consider various C# syntactical enhancements:

    - Use `Type x = new()` instead of specifying the type twice.

    - Use `records` for types that are not intended to be modified after creation.

    - Use [top-level statements](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements) for the primary application's code.

  - Ensure final sample ships without build warnings.

- Automation

  - Consider using a Docker container image for the build so you can ensure that you are using the latest .NET version

    ```yml
    build:
      runs-on: ubuntu-latest
      container: mcr.microsoft.com/dotnet/sdk:7.0
    ```

  - Consider adding a `workflow-dispatch` trigger for the build. This allows you to manually trigger builds in the GitHub web interface

    ```yml
    on:
      workflow_dispatch:
      push:    
        branches:
          - '*'
      pull_request:
        branches:
          - main
    ```

  - Consider reducing the steps in the build job to only run `dotnet build` and `dotnet test`. The restore step is implicitly ran if your packages aren't restored.
